config/routes.rb
Rails.application.routes.draw do

  # CHANNEL Routes
  mount ActionCable.server, at: '/cable'

  # SESSION Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  # USER Routes
  resources :users, only: [:new, :create]
  patch 'user', to: 'users#update'
  put 'user', to: 'users#update'
  get 'api_key', to: 'users#api_key'
  get 'new_key', to: 'users#new_key'
  
  #PRINTER STUFF Routes
  resources :printers
  resources :print_logs
  get 'reset_print_logs', to: "print_logs#reset_print_logs"

  #CONFIG Routes
  get 'config', to: 'config#show'
  get 'reload_config', to: 'config#reload'
  get 'download_config', to: 'config#download'
  post 'upload_config', to: 'config#upload'
  put 'edit_config', to: 'config#edit'

# API Routes
  namespace :api do
    namespace :v1 do
      get '/printers_api', to: 'printers_api#index'
      post '/printers_api', to: 'printers_api#create'

      get '/printers_api/show', to: 'printers_api#show'
      post '/printers_api/edit', to: 'printers_api#update'
      delete '/printers_api/delete', to: 'printers_api#destroy'

      get '/print_logs_api', to: 'print_logs_api#index'
      post '/print_logs_api', to: 'print_logs_api#create'

      post '/print_logs_api/edit', to: 'print_logs_api#update'
    end
  end

  root to: "static#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_flash.html.erb
<br>
<div class="flash">
	<% flash.each do |type, msg| %>
		<div class="alert alert-danger" role="alert">
			<%= msg %>
		</div>
	<% end %>
</div>

app/views/partials/_footer.html.erb
<div class="container-fluid bg-primary d-flex justify-content-center pt-1">
	<h5>Contact Us At: cbuprinting@gmail.com</h3>
</div>

app/views/partials/_header.html.erb
<header class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<%= link_to "RPL Manager", root_path, class: "navbar-brand" %>
		<div class="collapse navbar-collapse" id="navbarColor01">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	      	<%= link_to "Printers", root_path, class: "nav-link" %>
	      </li>
	      <li class="nav-item">
	        <%= link_to "Print Logs", print_logs_path, class: "nav-link" %>
	      </li>
	    </ul>
      <% if logged_in? %>
        <ul class="navbar-nav">
        	<li class="nav-item dropdown">
        		<%= link_to "Admin", "#", { class: "nav-link dropdown-toggle", "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false, "role": "button" } %>
        		<div class="dropdown-menu">
		        	<%= link_to "Config", config_path, class: "nav-link" %>
		        	<%= link_to "API Key", api_key_path, class: "nav-link" %>
		        	<div class="dropdown-divider"></div>
		        	<%= link_to "Logout", logout_path, class: "nav-link" %>
        		</div>
        	</li>
        </ul>
      <%else%>
        <%= link_to "Sign In", login_path, class: "btn btn-primary" %>
      <%end%>
	  </div>
	</nav>
</header>

app/views/partials/_log_table.html.erb
<div class="log-table">
  <table class="table table-sm table-striped table-dark">
    <thead class= "bg-dark">
      <tr>
        <th class= "bg-dark"><%= sortable "printer_name", "Printer" %> </th>
        <th class= "bg-dark"><%= sortable "created_at", "TimeStamp" %> </th>
        <th class= "bg-dark"><%= sortable "file_name", "File Name" %> </th>
        <th class= "bg-dark"><%= sortable "filament_weight", "Filament Weight" %> </th>
        <th class= "bg-dark"><%= sortable "print_time", "Print Time" %> </th>
        <th class= "bg-dark"><%= sortable "cost" %> </th>
        <th class= "bg-dark"></th>
      </tr>
    </thead>
    <tbody>
      <%= render print_logs %>
    </tbody>
  </table>
</div>

<div class="title-container text-light">
  <!--<h3>Cost of Successful Prints: $<%= number_with_precision total_cost(print_logs), :precision => 2 %></h3> -->
</div>


app/views/partials/_navbar.html.erb
<header class="w-100">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<%= link_to "RPL Manager", root_path, class: "navbar-brand" %>
		<div class="collapse navbar-collapse" id="navbarColor01">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	      	<%= link_to "Printers", printers_path, class: "nav-link" %>
	      </li>
	      <li class="nav-item">
	        <%= link_to "Print Logs", print_logs_path, class: "nav-link" %>
	      </li>
	    </ul>
      <% if logged_in? %>
        <ul class="navbar-nav">
        	<li class="nav-item dropdown">
        		<%= link_to "Admin", "#", { class: "nav-link dropdown-toggle", "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false, "role": "button" } %>
        		<div class="dropdown-menu">
		        	<%= link_to "Config", config_path, class: "nav-link" %>
		        	<%= link_to "API Key", api_key_path, class: "nav-link" %>
		        	<div class="dropdown-divider"></div>
		        	<%= link_to "Logout", logout_path, class: "nav-link" %>
        		</div>
        	</li>
        </ul>
      <%else%>
        <%= link_to "Sign In", login_path, class: "btn btn-primary" %>
      <%end%>
	  </div>
	</nav>
</header>