config/routes.rb
Rails.application.routes.draw do

  # CHANNEL Routes
  mount ActionCable.server, at: '/cable'

  # SESSION Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  # USER Routes
  resources :users, only: [:new, :create]
  patch 'user', to: 'users#update'
  put 'user', to: 'users#update'
  get 'api_key', to: 'users#api_key'
  get 'new_key', to: 'users#new_key'
  
  #PRINTER STUFF Routes
  resources :printers
  resources :print_logs
  get 'reset_print_logs', to: "print_logs#reset_print_logs"

  #CONFIG Routes
  get 'config', to: 'config#show'
  get 'reload_config', to: 'config#reload'
  get 'download_config', to: 'config#download'
  post 'upload_config', to: 'config#upload'
  put 'edit_config', to: 'config#edit'

# API Routes
  namespace :api do
    namespace :v1 do
      get '/printers_api', to: 'printers_api#index'
      post '/printers_api', to: 'printers_api#create'

      get '/printers_api/show', to: 'printers_api#show'
      post '/printers_api/edit', to: 'printers_api#update'
      delete '/printers_api/delete', to: 'printers_api#destroy'

      get '/print_logs_api', to: 'print_logs_api#index'
      post '/print_logs_api', to: 'print_logs_api#create'

      post '/print_logs_api/edit', to: 'print_logs_api#update'
    end
  end

  root to: "static#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/config_controller.rb
class ConfigController < ApplicationController
  def show
  	@config = helpers.get_config
  end

  def download
  	send_file File.join(Rails.root, 'public', 'config', 'log_cost_calculation.yml')
  end

  def upload
  	uploaded_io = params[:config_file]
    File.open(Rails.root.join('public', 'config', 'log_cost_calculation.yml'), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    redirect_to reload_config_path
  end

  def reload
  	helpers.reload_cost_config
    redirect_to print_logs_path
  end

  def edit
    
  end
end

app/helpers/config_helper.rb
module ConfigHelper
end

app/views/config/download.html.erb
<h1>Config#download</h1>
<p>Find me in app/views/config/download.html.erb</p>

app/views/config/reload.html.erb
<h1>Config#reload</h1>
<p>Find me in app/views/config/reload.html.erb</p>

app/views/config/show.html.erb
<div class="title-container text-light">
	<h1>Configuration</h1>
	
	<div class="float-left m-2">
		<%= link_to 'Download Cost Config', download_config_path, class: "btn btn-default border rounded text-light" %>
	</div>
	
	<div class="float-right p-1 border rounded">
		<%= form_with url: upload_config_path, id: "upload-form" do |f| %>
			<div class="form-group">
				<%= f.file_field :config_file, id: "upload-field", class: "text-light" %>
				<%= f.submit "Upload Cost Config", class: "submit" %>
			</div>
		<% end %>
	</div>
</div>


<div class="text-center">
	<%= form_with url: edit_config_path do |f| %>
		<h2><%= f.label :variables, class:"text-secondary" %></h2>
		<div class="form-group">
			<%= f.text_field :variable, value: "@time", readonly: true %>
		</div>

		<div class="form-group">
			<%= f.text_field :variable, value: "@weight", readonly: true %>
		</div>
	<%end%>

	<%= form_with method: :put, url: edit_config_path do |f| %>
		<h2><%= f.label :constants, class:"text-secondary" %></h2>
		<div class="config-constants">
			<% @config["variables"].each do |key, value| %>
				<div class="config-constants mx-4">
					<div class="form-group">
						<%= f.text_field key, value: key, class:"form-control-plaintext text-success text-center", readonly: true %>
				    	<%= f.text_field :value, value: value, readonly: true %>
					</div>
				</div>
			<%end%>
		</div>
	<%end%>

	<%= form_with method: :put, url: edit_config_path do |f| %>
		<h2><%= f.label :calculations, class:"text-secondary" %></h2>
		<% @config["calculations"].each do |key, value| %>
			<div class="form-group">
				<%= f.text_field :method, value: key, class:"form-control-plaintext text-warning text-center", readonly: true %>
		    <%= f.text_area :body, value: value, rows: 3, cols: 80, class:"form-control", readonly: true %>
			</div>
		<%end%>
	<%end%>
</div>

app/views/config/upload.html.erb
<h1>Config#upload</h1>
<p>Find me in app/views/config/upload.html.erb</p>