config/routes.rb
Rails.application.routes.draw do

  # CHANNEL Routes
  mount ActionCable.server, at: '/cable'

  # SESSION Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  # USER Routes
  resources :users, only: [:new, :create]
  patch 'user', to: 'users#update'
  put 'user', to: 'users#update'
  get 'api_key', to: 'users#api_key'
  get 'new_key', to: 'users#new_key'
  
  #PRINTER STUFF Routes
  resources :printers
  resources :print_logs
  get 'reset_print_logs', to: "print_logs#reset_print_logs"

  #CONFIG Routes
  get 'config', to: 'config#show'
  get 'reload_config', to: 'config#reload'
  get 'download_config', to: 'config#download'
  post 'upload_config', to: 'config#upload'
  put 'edit_config', to: 'config#edit'

# API Routes
  namespace :api do
    namespace :v1 do
      get '/printers_api', to: 'printers_api#index'
      post '/printers_api', to: 'printers_api#create'

      get '/printers_api/show', to: 'printers_api#show'
      post '/printers_api/edit', to: 'printers_api#update'
      delete '/printers_api/delete', to: 'printers_api#destroy'

      get '/print_logs_api', to: 'print_logs_api#index'
      post '/print_logs_api', to: 'print_logs_api#create'

      post '/print_logs_api/edit', to: 'print_logs_api#update'
    end
  end

  root to: "static#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/print_log.rb
class PrintLog < ApplicationRecord
  belongs_to :printer

  # Defined "each" method so that "total_cost" helper method
  # will work when a single PrintLog is passed instead
  # of a list of PrintLogs
  def each
  	yield(self)
  end

  def self.to_csv
  	header = %w[created_at printer_name file_name filament_weight print_time cost status]

  	CSV.generate(headers: true) do |csv|
  		csv << header

  		all.each do |log|
  			csv << log.attributes.values_at(*header)
  		end
  	end
  end
end

app/controllers/print_logs_controller.rb
require 'csv'

class PrintLogsController < ApplicationController
  before_action :set_print_log, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:index, :show]

  # GET /print_logs
  # GET /print_logs.json
  def index
    @print_logs = PrintLog.order(helpers.sort_column => helpers.sort_direction).all
    respond_to do |format|
      format.html
      format.csv {send_data @print_logs.to_csv}
    end
  end

  # GET /print_logs/1
  # GET /print_logs/1.json
  def show
  end

  # GET /print_logs/new
  def new
    @print_log = PrintLog.new
  end

  # GET /print_logs/1/edit
  def edit
  end

  # POST /print_logs
  # POST /print_logs.json
  def create
    params[:print_log][:printer_id] = Printer.find_by(name: form_fields(:printer_name)).id
    @print_log = PrintLog.new(print_log_params)

    respond_to do |format|
      if @print_log.save
        format.html { redirect_to @print_log, notice: 'Print log was successfully created.' }
        format.json { render :show, status: :created, location: @print_log }
      else
        format.html { render :new }
        format.json { render json: @print_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /print_logs/1
  # PATCH/PUT /print_logs/1.json
  def update
    respond_to do |format|
      if @print_log.update(print_log_params)
        format.html { redirect_to @print_log, notice: 'Print log was successfully updated.' }
        format.json { render :show, status: :ok, location: @print_log }
      else
        format.html { render :edit }
        format.json { render json: @print_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /print_logs/1
  # DELETE /print_logs/1.json
  def destroy
    @print_log.destroy
    respond_to do |format|
      format.html { redirect_to print_logs_path, notice: 'Print log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reset_print_logs
    PrintLog.destroy_all
    respond_to do |format|
      format.html { redirect_to print_logs_path, notice: 'Print logs were successfully destroyed.' }
      format.json { head :no_content }
    end
  end   

  private
    # Use callbacks to share common setup or constraints between actions.
    def form_fields(key)
      params[:print_log][key]
    end

    def set_print_log
      @print_log = PrintLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def print_log_params
      params.require(:print_log).permit(:printer_id, :printer_name, :file_name, :filament_weight, :print_time, :cost, :status)
    end
end

app/helpers/print_logs_helper.rb
module PrintLogsHelper
	# Loops through all the PrintLogs on a given page
	# and returns the sum of their costs
	# *** NOTE ***
	# This implementation could be more efficient if you 
	# increment sum in the views.
	def total_cost(print_logs)
		cost = 0
		print_logs.each do |log|
			cost += calculate_log_cost(log) unless log.status == 3
		end
		cost
	end
end

app/views/print_logs/_form.html.erb
<%= form_with(model: print_log, local: true) do |form| %>
  <% if print_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(print_log.errors.count, "error") %> prohibited this print_log from being saved:</h2>

      <ul>
      <% print_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :printer_name, class:"text-light" %>
    <%= form.text_field :printer_name, id: :print_log_printer_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :file_name, class:"text-light" %>
    <%= form.text_field :file_name, id: :print_log_file_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :filament_weight, class:"text-light" %>
    <%= form.text_field :filament_weight, id: :print_log_filament_weight, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :print_time, class:"text-light" %>
    <%= form.text_field :print_time, id: :print_log_print_time, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cost, class:"text-light" %>
    <%= form.text_field :cost, id: :print_log_cost, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status, class:"text-light" %>
    <%= form.text_field :status, id: :print_log_status, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/print_logs/_print_log.html.erb
<div class="print_logs">
  <div class="print_log">
    <div class="thumbnail">
      <div class="text-light">
          <tr>
            <td> <%= link_to print_log.printer_name, print_log_path(print_log), class: colorize(print_log.status) %> </td>
            <td> <%= print_log.created_at.to_s.chop.chop.chop %> </td>
            <td> <%= truncate(print_log.file_name, length: 30) %> </td>
            <td> <%= print_log.filament_weight %>g </td>
            <td> <%= print_log.print_time %> min </td>
            <td> $<%= number_with_precision calculate_log_cost(print_log), :precision => 2 %> </td>
            <td class="text-right"> 
              <% if logged_in? %>
                <%= link_to "Edit", edit_print_log_path(print_log), class: "btn btn-default border rounded text-warning p-0 px-1" %>
                <%= link_to 'Delete', print_log, method: :delete, data: { confirm: 'Are you sure?' }, 
                class: "btn btn-default border rounded text-danger p-0 px-1" %> 
              <%end%>
            </td>
          </tr>
      </div>
    </div>
  </div>
</div>

app/views/print_logs/edit.html.erb
<div class="title-container text-light">
	<h1>Editing Print Log</h1>
</div>

<%= render 'form', print_log: @print_log %>

app/views/print_logs/index.html.erb
<div class="title-container d-flex bd-highlight text-light ">
  	<h1 class="p-2 flex-grow-1 bd-highlight">Print Logs</h1>
  	<% if logged_in? %>
		<%= link_to 'Download Print Logs', print_logs_path(format: :csv), 
		class: "btn btn-default border rounded text-light p-2 bd-highlight align-self-center" %>
		<%= link_to 'Delete All Print Logs', reset_print_logs_path,  data: { confirm: 'Are you sure you want to reset print logs?' },
		class: "btn btn-danger border rounded text-light p-2 bd-highlight align-self-center" %>
	<%end%>
</div>

<% if logged_in? %>
	<%= link_to 'New Print Log', new_print_log_path, 
	class: "btn btn-default border rounded text-light" %>
<%end%>

<%= render partial: 'partials/log_table', locals: { print_logs: @print_logs } %>

app/views/print_logs/new.html.erb
<div class="title-container text-light">
	<h1>New Print Log</h1>
</div>

<%= render 'form', print_log: @print_log %>

app/views/print_logs/show.html.erb
<div class="title-container text-light">
  <h1><%= @print_log.file_name %></h1>
</div>

<%= render partial: 'partials/log_table', locals: { print_logs: @print_log } %>