config/routes.rb
Rails.application.routes.draw do

  # CHANNEL Routes
  mount ActionCable.server, at: '/cable'

  # SESSION Routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  # USER Routes
  resources :users, only: [:new, :create]
  patch 'user', to: 'users#update'
  put 'user', to: 'users#update'
  get 'api_key', to: 'users#api_key'
  get 'new_key', to: 'users#new_key'
  
  #PRINTER STUFF Routes
  resources :printers
  resources :print_logs
  get 'reset_print_logs', to: "print_logs#reset_print_logs"

  #CONFIG Routes
  get 'config', to: 'config#show'
  get 'reload_config', to: 'config#reload'
  get 'download_config', to: 'config#download'
  post 'upload_config', to: 'config#upload'
  put 'edit_config', to: 'config#edit'

# API Routes
  namespace :api do
    namespace :v1 do
      get '/printers_api', to: 'printers_api#index'
      post '/printers_api', to: 'printers_api#create'

      get '/printers_api/show', to: 'printers_api#show'
      post '/printers_api/edit', to: 'printers_api#update'
      delete '/printers_api/delete', to: 'printers_api#destroy'

      get '/print_logs_api', to: 'print_logs_api#index'
      post '/print_logs_api', to: 'print_logs_api#create'

      post '/print_logs_api/edit', to: 'print_logs_api#update'
    end
  end

  root to: "static#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/printer.rb
class Printer < ApplicationRecord
	validates_uniqueness_of :name
	has_many :print_logs
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:index, :show]

  # GET /printers
  # GET /printers.json
  def index
    @printers = Printer.order(:name).all
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
    @print_logs = PrintLog.order(helpers.sort_column => helpers.sort_direction).where(printer_name: @printer.name)
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        broadcast
        format.html { redirect_to printers_path, notice: 'Printer created successfully!' }
      else
        format.html { render :new }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        broadcast
        format.html { redirect_to printers_path, notice: 'Printer Updated successfully!' }
      else
        format.html { render :edit }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    flash.now[:notice] = 'Printer was successfully destroyed.'
    broadcast
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def printer_params
      params.require(:printer).permit(:name, :status)
    end

    def broadcast
      ActionCable.server.broadcast "printers_channel",
                                    printer: @printer
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
	
end

app/views/printers/_form.html.erb
<%= form_with(model: printer) do |form| %>
  <% if printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(printer.errors.count, "error") %> prohibited this printer from being saved:</h2>

      <ul>
      <% printer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class:"text-light" %>
    <%= form.text_field :name, id: :printer_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status, class:"text-light" %>
    <%= form.number_field :status, id: :printer_status, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/printers/_printer.html.erb
<div class="printer" data-id=<%= printer.id %>>
  <div class="card border-warning mb-3" style="max-width: 20rem;">
    <div class="card-header"><%= link_to printer.name, printer_path(printer), class: colorize(printer.status) %></div>
    <div class="card-body">
      <h4 class="card-title">Status</h4>
      <p class="card-text">
        <% if logged_in? %>
          <%= link_to "Edit", edit_printer_path(printer), class: "btn btn-default border rounded text-warning p-0 px-2" %>
          <%= link_to 'Delete', printer, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger p-1" %>
        <%end%>
      </p>
    </div>
  </div>
</div>

app/views/printers/edit.html.erb
<div class="title-container text-light">
	<h1>Editing Printer</h1>
</div>

<%= render 'form', printer: @printer %>

app/views/printers/index.html.erb
<div class="container-fluid fullscreen">
	<div class="title-container text-light">
	  <h1>Printers</h1>
	  <%= link_to 'New Printer', new_printer_path, class: "btn btn-default border rounded text-light" %>
	</div>

	<div class="printers" id="printer-container">
	  <%= render @printers %>
	</div>
</div>

app/views/printers/new.html.erb
<div class="title-container text-light">
	<h1>New Printer</h1>
</div>

<%= render 'form', printer: @printer %>

app/views/printers/show.html.erb
<div class="title-container text-light">
  <h1><%= @printer.name %></h1>
</div>

<%= render partial: 'partials/log_table', locals: { print_logs: @print_logs } %>